# GitHub Pages configuration
# Only include frontend static files

include:
  - index.html
  - 404.html
  - pages
  - css
  - js
  - assets
  - robots.txt
  - sitemap.xml
  - CNAME

exclude:
  - backend
  - deployment
  - docs
  - tests
  - ref
  - oldchatVLA
  - requirements.txt
  - requirements-minimal.txt
  - Dockerfile
  - .railway-trigger
  - .railwayignore
  - "*.py"
  - "*.pyc"
  - "__pycache__"
  - ".git"
  - ".github"
  - "*.md"
  - "*.log"
  - "*.yml"
  - "*.yaml"
  - "*.toml"
  - "*.json"
  - frontend/debug-firebase.html
  - frontend/index.html
  - frontend/pages
  - frontend/css
  - frontend/js
  - frontend/assets