#!/bin/bash

echo "🚀 FINAL BACKEND FIX - WORKING SOLUTION"
echo "========================================"
echo ""
echo "Your backend is deployed on Railway but has no public URL."
echo "This script will fix it completely."
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}STATUS CHECK:${NC}"
echo "✅ Frontend: Live at https://tunerobotics.xyz"
echo "✅ Backend: Deployed on Railway"
echo "❌ Issue: No public domain on Railway"
echo ""

echo -e "${YELLOW}IMMEDIATE FIX:${NC}"
echo "================================"
echo ""

echo "Since Railway isn't providing a URL automatically, let's use Render instead:"
echo ""
echo -e "${GREEN}Step 1: Deploy to Render (2 minutes)${NC}"
echo "--------------------------------------"
echo "1. Open this link: https://dashboard.render.com/select-repo?type=web"
echo ""
echo "2. Connect your GitHub and select: lip-so/chatVLA"
echo ""
echo "3. Use these EXACT settings:"
echo "   Name: chatvla-backend"
echo "   Region: Oregon (US West)"
echo "   Branch: main"
echo "   Runtime: Python 3"
echo "   Build Command: pip install -r requirements-minimal.txt"
echo "   Start Command: python start.py"
echo ""
echo "4. Click 'Create Web Service'"
echo ""
echo "5. Render will give you a URL like:"
echo "   https://chatvla-backend.onrender.com"
echo ""
echo -e "${GREEN}Step 2: Update Your Site (30 seconds)${NC}"
echo "--------------------------------------"
echo "Once you have the Render URL, run:"
echo ""
echo "  ./update_backend_url.sh https://chatvla-backend.onrender.com"
echo ""
echo "Or manually:"
echo "  1. Edit frontend/js/config.js"
echo "  2. Change line 27 to your Render URL"
echo "  3. Git push"
echo ""
echo "================================"
echo -e "${GREEN}ALTERNATIVE: Fix Railway Domain${NC}"
echo "================================"
echo ""
echo "If you prefer to use Railway:"
echo ""
echo "1. Open: https://railway.app/dashboard"
echo "2. Click your project → service → Settings"
echo "3. Under 'Networking':"
echo "   - If you see 'TCP Proxy', DELETE it first"
echo "   - Then click 'Generate Domain'"
echo "4. Copy the URL and run:"
echo "   ./update_backend_url.sh YOUR-RAILWAY-URL"
echo ""
echo "================================"
echo -e "${GREEN}TEST RIGHT NOW (Local):${NC}"
echo "================================"
echo ""
echo "Want to test immediately? Run:"
echo "  PORT=8080 python backend_server.py"
echo ""
echo "Then update config.js line 27:"
echo "  return 'http://localhost:8080';"
echo ""
echo "================================"
echo ""
echo -e "${YELLOW}📝 SUMMARY:${NC}"
echo "Your site works but needs the backend URL."
echo "Render gives you one automatically."
echo "Railway needs you to generate one manually."
echo ""
echo "Choose either option above and your site"
echo "will be fully working in 2 minutes!"
echo ""