#!/bin/bash

echo "🔍 Finding Your Railway Backend URL"
echo "===================================="
echo ""
echo "Please follow these steps:"
echo ""
echo "1️⃣  Open your Railway dashboard:"
echo "   https://railway.app/dashboard"
echo ""
echo "2️⃣  Click on your 'chatVLA' project"
echo ""
echo "3️⃣  Click on the deployment (should show as 'Active')"
echo ""
echo "4️⃣  In the deployment details, look for:"
echo "   - Click 'Settings' tab"
echo "   - Scroll to 'Networking' section"
echo "   - Click 'Generate Domain' button"
echo ""
echo "5️⃣  Copy your URL (it will look like):"
echo "   https://chatvla-production-XXXX.up.railway.app"
echo "   or"
echo "   https://CUSTOM-NAME.up.railway.app"
echo ""
echo "6️⃣  Once you have your URL, run this command:"
echo ""
echo "   ./update_backend_url.sh YOUR_RAILWAY_URL"
echo ""
echo "Example:"
echo "   ./update_backend_url.sh https://chatvla-production-abc123.up.railway.app"
echo ""
echo "❓ Can't find the URL? Try these:"
echo "   - Make sure deployment shows 'Active' status"
echo "   - If no domain exists, click 'Generate Domain'"
echo "   - If deployment failed, check the logs"
echo ""