[phases.setup]
nixPkgs = ["gcc", "g++", "python311", "libffi", "openssl"]
aptPkgs = ["libfreetype-dev", "pkg-config", "libpng-dev"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[providers]
python = "3.11"

[start]
cmd = "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT backend.plug_and_play.wsgi:application"