#!/bin/bash

echo "🚀 Quick Fix for Backend Offline Error"
echo "======================================"
echo ""
echo "Your backend IS deployed on Railway!"
echo "We just need to connect it to your frontend."
echo ""
echo "📍 STEP 1: Get Your Railway URL"
echo "--------------------------------"
echo "1. Open: https://railway.app/dashboard"
echo "2. Click on your 'chatVLA' project"
echo "3. Click on your service"
echo "4. Go to 'Settings' tab"
echo "5. Find 'Networking' section"
echo "6. Click 'Generate Domain'"
echo "7. Copy the URL"
echo ""
echo "Can't see 'Generate Domain' button?"
echo "- Make sure deployment shows 'Active'"
echo "- If you see a TCP Proxy, delete it first"
echo "- Then 'Generate Domain' will appear"
echo ""
echo "📝 STEP 2: Update Your Frontend"
echo "--------------------------------"
echo "Once you have your Railway URL, run:"
echo ""
echo "  ./update_backend_url.sh YOUR_RAILWAY_URL"
echo ""
echo "Example:"
echo "  ./update_backend_url.sh https://chatvla-production-abc123.up.railway.app"
echo ""
echo "🔧 ALTERNATIVE: Manual Update"
echo "------------------------------"
echo "If the script doesn't work, manually edit:"
echo "  File: frontend/js/config.js"
echo "  Line 26: return 'YOUR_RAILWAY_URL';"
echo ""
echo "Then push:"
echo "  git add frontend/js/config.js"
echo "  git commit -m 'Add Railway backend URL'"
echo "  git push origin main"
echo ""
echo "✅ That's it! Your site will work in 1-2 minutes!"