# Railway Configuration for DataBench with ML Dependencies - v2.1
[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements-full.txt && python -c 'import torch; import transformers; print(\"Dependencies verified\")'"

[deploy]
startCommand = "python3 start_railway.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
healthcheckInterval = 30

[env]
PYTHONUNBUFFERED = "1"
PORT = "10000"
PYTHONPATH = "/app/databench:/app"
# Memory optimization for Railway
PYTORCH_CUDA_ALLOC_CONF = "max_split_size_mb:512"
TOKENIZERS_PARALLELISM = "false"
# HuggingFace cache optimization
HF_HOME = "/tmp/huggingface"
TRANSFORMERS_CACHE = "/tmp/huggingface/transformers"
HF_DATASETS_CACHE = "/tmp/huggingface/datasets" 