[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements-full.txt"

[deploy]
startCommand = "python3 multi_api.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHONUNBUFFERED = "1"
PORT = "10000"
PYTHONPATH = "/app/databench" 