#!/bin/bash

echo "🔍 RAILWAY DEPLOYMENT STATUS CHECK"
echo "===================================="
echo ""
echo "Let's diagnose your Railway deployment..."
echo ""

# Check current frontend configuration
echo "1️⃣ Current Frontend Configuration:"
echo "-----------------------------------"
if grep -q "chatvla-mock-backend.glitch.me" frontend/js/config.js; then
    echo "❌ Frontend is still using MOCK backend"
    echo "   This means Railway URL hasn't been configured yet"
else
    CURRENT_URL=$(grep "return 'https://" frontend/js/config.js | grep -o "https://[^']*" | head -1)
    echo "✅ Frontend is configured with: $CURRENT_URL"
fi
echo ""

echo "2️⃣ What You Should See in Railway Dashboard:"
echo "---------------------------------------------"
echo "Go to: https://railway.app/dashboard"
echo ""
echo "Your 'chatVLA' project should show:"
echo "  • Service Status: ✅ Active (green)"
echo "  • Latest Deployment: ✅ Success"
echo "  • Build Logs: No errors"
echo "  • Deploy Logs: 'Starting Flask app on port 8080'"
echo ""

echo "3️⃣ How to Get Your Railway URL:"
echo "---------------------------------"
echo "METHOD A: Check Service Page"
echo "  1. Click on your service in Railway"
echo "  2. Look at the TOP of the panel"
echo "  3. You might see the URL already displayed"
echo ""
echo "METHOD B: Add PORT Variable (triggers domain)"
echo "  1. Click Variables tab"
echo "  2. Add: PORT = 8080"
echo "  3. Save and wait for redeploy"
echo "  4. Domain option will appear"
echo ""
echo "METHOD C: Use Railway CLI"
echo "  brew install railway"
echo "  railway login"
echo "  railway link"
echo "  railway domain"
echo ""

echo "4️⃣ Common Issues & Fixes:"
echo "--------------------------"
echo "❌ If deployment is FAILING:"
echo "   - Check Deploy Logs for errors"
echo "   - Common: missing dependencies, wrong start command"
echo ""
echo "❌ If deployment is SUCCESS but no domain option:"
echo "   - Add PORT=8080 to Variables"
echo "   - Wait for redeploy"
echo ""
echo "❌ If you see 'TCP Proxy' instead of HTTP:"
echo "   - Delete the TCP Proxy"
echo "   - Add PORT variable"
echo "   - Domain option will appear"
echo ""

echo "5️⃣ Once You Have Your Railway URL:"
echo "-----------------------------------"
echo "Run this command with YOUR Railway URL:"
echo "./update_backend_url.sh https://chatvla-production-xxxx.up.railway.app"
echo ""
echo "This will:"
echo "  • Update frontend/js/config.js"
echo "  • Commit and push to GitHub"
echo "  • GitHub Pages will update in 1-2 minutes"
echo "  • Your site will be fully functional!"
echo ""

echo "📊 CURRENT STATUS:"
echo "=================="
echo "✅ Frontend: https://tunerobotics.xyz (GitHub Pages)"
echo "⚠️  Backend: Waiting for Railway URL configuration"
echo ""
echo "ACTION REQUIRED: Get your Railway URL and run update script!"