[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 wsgi:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30

[[services]]
name = "web"
internalPort = 8080

[env]
PYTHONPATH = "/app:/app/backend"
FLASK_ENV = "production"
PYTHON_VERSION = "3.11"