[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 databench_api.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
PYTHONPATH = "/app/databench"
PYTHONUNBUFFERED = "1" 