[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 30

[[services]]
name = "web"
internalPort = 8080

[env]
PORT = "8080"
FIREBASE_OPTIONAL = "true"