[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements-light.txt"

[deploy]
startCommand = "python3 databench_api_light.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
PYTHONPATH = "/app/databench"
PYTHONUNBUFFERED = "1" 