services:
  - type: web
    name: chatvla-backend
    runtime: python
    buildCommand: pip install -r requirements-production.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: FIREBASE_OPTIONAL
        value: true
    autoDeploy: true