services:
  - type: web
    name: chatvla-backend
    runtime: python
    buildCommand: pip install -r requirements-minimal.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true