# SO-100 Follower (5-DOF desktop arm) Configuration
robot_type: so100
dof: 5
communication:
  type: serial
  baud_rate: 1000000
  port_pattern: "/dev/ttyUSB*"
  timeout: 1.0

deployment_mode: comprehensive
installation_date: 2025-08-05T20:54:19.805897
cloud_deployment: true
features:
  usb_detection: True
  databench: true
  real_hardware: true
