services:
  - type: web
    name: tune-robotics
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/plug_and_play/app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: false
