# DataBench Configuration File
# This file contains all configurable parameters for robotics dataset evaluation metrics

# ==============================================================================
# VISUAL PROCESSING PARAMETERS
# ==============================================================================
visual:
  # Number of frames to sample from videos for analysis
  num_frames: 8
  # Maximum number of samples to process for diversity analysis
  sample_size: 1000
  # Video loading timeout in seconds
  video_timeout: 30
  # Supported video codecs (for fallback handling)
  supported_codecs: ["mp4", "avi", "mov", "mkv"]

# ==============================================================================
# ROBOT ACTION QUALITY PARAMETERS
# ==============================================================================
robot_action_quality:
  # Joint limits for common robot configurations (in radians or meters)
  # These will be used if robot-specific limits are not available
  joint_limits:
    # 6-DOF manipulator (e.g., UR5, Franka Panda)
    6dof:
      shoulder_pan: [-3.14, 3.14]      # -180 to 180 degrees
      shoulder_lift: [-1.57, 1.57]     # -90 to 90 degrees  
      elbow_flex: [-2.36, 2.36]        # -135 to 135 degrees
      wrist_flex: [-1.57, 1.57]        # -90 to 90 degrees
      wrist_roll: [-3.14, 3.14]        # -180 to 180 degrees
      gripper: [0.0, 1.0]              # 0 (closed) to 1 (open)
    
    # 7-DOF manipulator (e.g., Franka Panda, Kuka LBR)
    7dof:
      shoulder_pan: [-2.97, 2.97]      # ±170 degrees
      shoulder_lift: [-1.76, 1.76]     # ±100 degrees
      elbow_flex: [-2.90, 2.90]        # ±166 degrees
      wrist_flex: [-3.07, -0.07]       # -176 to -4 degrees
      wrist_roll: [-2.18, 2.18]        # ±125 degrees
      wrist_flex_2: [-3.75, 3.75]      # ±215 degrees
      wrist_roll_2: [-2.18, 2.18]      # ±125 degrees
      gripper: [0.0, 0.08]             # 0 (closed) to 8cm (open)
  
  # Default joint limits for unknown configurations
  default_joint_limits: [-3.14, 3.14]  # ±180 degrees
  
  # Quality thresholds
  thresholds:
    smoothness_threshold: 0.1          # Maximum normalized jerk for smooth motion
    consistency_threshold: 0.05        # Maximum relative difference between state and action
    velocity_threshold: 0.5            # Maximum normalized velocity per timestep
    discontinuity_threshold: 0.2       # Maximum normalized jump between timesteps
    gripper_change_rate_min: 0.05      # Minimum gripper state change rate
    gripper_change_rate_max: 0.3       # Maximum gripper state change rate

# ==============================================================================
# TRAJECTORY QUALITY PARAMETERS  
# ==============================================================================
trajectory_quality:
  # Synchronization thresholds (in milliseconds)
  sync_thresholds:
    gold: 5      # Excellent synchronization
    silver: 20   # Good synchronization  
    bronze: 50   # Acceptable synchronization
  
  # Action frequency thresholds (in Hz)
  freq_thresholds:
    gold: 30     # High frequency (excellent)
    silver: 10   # Medium frequency (good)
    bronze: 5    # Low frequency (acceptable)
  
  # Minimum number of samples for frequency analysis
  min_samples_for_frequency: 10
  
  # Data completeness threshold (fraction of non-null values)
  completeness_threshold: 0.95

# ==============================================================================
# DATASET COVERAGE PARAMETERS
# ==============================================================================
dataset_coverage:
  # Number of trajectories thresholds
  trajectory_thresholds:
    gold: 50000    # Large dataset
    silver: 1000   # Medium dataset
    bronze: 100    # Small dataset
  
  # Number of unique tasks thresholds
  task_thresholds:
    gold: 10       # High task diversity
    silver: 4      # Medium task diversity  
    bronze: 1      # Single task
  
  # Minimum samples for visual diversity analysis
  min_visual_samples: 10
  
  # Failure analysis parameters
  failure_rate_threshold: 0.1  # 10% failure rate is acceptable

# ==============================================================================
# ACTION CONSISTENCY PARAMETERS
# ==============================================================================
action_consistency:
  # Visual processing parameters
  num_frames: 8
  
  # Consistency analysis parameters
  min_episodes_for_cross_analysis: 2
  min_sequence_length: 5
  correlation_threshold: 0.1  # Minimum correlation to consider meaningful
  
  # Temporal consistency parameters
  smoothness_window: 3  # Window size for temporal smoothness analysis
  
  # Weights for different consistency types
  weights:
    visual_text: 0.3
    action_observation: 0.3
    cross_episode: 0.2
    temporal: 0.2

# ==============================================================================
# VISUAL DIVERSITY PARAMETERS
# ==============================================================================
visual_diversity:
  # Frame sampling parameters
  num_frames: 8
  sample_size: 1000
  
  # Clustering parameters
  min_samples_for_clustering: 10
  n_clusters: 5
  random_state: 42
  
  # Diversity calculation weights
  weights:
    pairwise: 0.4      # Pairwise distance diversity
    cluster: 0.3       # Cluster-based diversity  
    entropy: 0.3       # Entropy-based diversity

# ==============================================================================
# HIGH FIDELITY VISION PARAMETERS
# ==============================================================================
high_fidelity_vision:
  # Resolution thresholds
  resolution_thresholds:
    gold: [1920, 1080]    # Full HD or higher
    silver: [1280, 720]   # HD
    bronze: [640, 480]    # VGA
  
  # Frame rate thresholds (fps)
  framerate_thresholds:
    gold: 30
    silver: 15  
    bronze: 10
  
  # Multi-view scoring
  single_view_penalty: 0.3    # Penalty for single camera setups
  multi_view_bonus: 0.2       # Bonus for multiple camera views
  
  # Environment verification parameters
  blur_threshold: 100         # Laplacian variance threshold for blur detection
  brightness_range: [20, 235] # Acceptable brightness range
  
  # Prompt quality parameters
  min_prompt_length: 10       # Minimum characters for meaningful prompt
  max_prompt_length: 200      # Maximum reasonable prompt length

# ==============================================================================
# GENERAL PARAMETERS
# ==============================================================================
general:
  # Logging configuration
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Processing parameters
  max_workers: 4              # Number of parallel workers for processing
  chunk_size: 100             # Batch size for processing large datasets
  
  # Default values
  default_score: 0.5          # Neutral score when analysis fails
  
  # File handling
  supported_video_extensions: [".mp4", ".avi", ".mov", ".mkv", ".webm"]
  supported_data_extensions: [".parquet", ".csv", ".json"]
  
  # Memory management
  max_frames_in_memory: 1000  # Maximum video frames to keep in memory
  
# ==============================================================================
# ROBOT-SPECIFIC CONFIGURATIONS
# ==============================================================================
robots:
  # Franka Panda configuration
  franka_panda:
    dof: 7
    joint_limits:
      - [-2.97, 2.97]   # joint1
      - [-1.76, 1.76]   # joint2  
      - [-2.90, 2.90]   # joint3
      - [-3.07, -0.07]  # joint4
      - [-2.18, 2.18]   # joint5
      - [-3.75, 3.75]   # joint6
      - [-2.18, 2.18]   # joint7
    gripper_limits: [0.0, 0.08]
    max_velocity: 1.5  # rad/s
    gripper_joint: null  # Franka has separate gripper control
    
  # UR5 configuration  
  ur5:
    dof: 6
    joint_limits:
      - [-6.28, 6.28]   # base
      - [-6.28, 6.28]   # shoulder
      - [-3.14, 3.14]   # elbow
      - [-6.28, 6.28]   # wrist1
      - [-6.28, 6.28]   # wrist2  
      - [-6.28, 6.28]   # wrist3
    gripper_limits: [0.0, 1.0]
    max_velocity: 3.15  # rad/s
    gripper_joint: null  # UR5 has separate gripper control
    
  # Generic 6DOF robot (fallback)
  generic_6dof:
    dof: 6
    joint_limits:
      - [-3.14, 3.14]   # joint1
      - [-1.57, 1.57]   # joint2
      - [-2.36, 2.36]   # joint3
      - [-1.57, 1.57]   # joint4
      - [-3.14, 3.14]   # joint5
      - [0.0, 1.0]      # gripper
    gripper_limits: [0.0, 1.0]
    max_velocity: 2.0   # rad/s
    gripper_joint: 5     # Last joint is gripper
    
  # SO101 Follower configuration (6-DOF manipulator)
  so101_follower:
    dof: 6
    joint_limits:
      - [-3.14, 3.14]   # shoulder_pan
      - [-1.57, 1.57]   # shoulder_lift  
      - [-2.36, 2.36]   # elbow_flex
      - [-1.57, 1.57]   # wrist_flex
      - [-3.14, 3.14]   # wrist_roll
      - [0.0, 1.0]      # gripper
    gripper_limits: [0.0, 1.0]
    max_velocity: 2.0   # rad/s
    gripper_joint: 5     # Last joint is gripper 